### ISSUE TITLE
is 11straps a bootstrap port? 

### ISSUE THREAD

**Issue by nniiicc** [PugetSoundClinic-PIT/PugetSoundClinic-PIT.github.io#28]
Eva - can we just dump in a boostrap theme and use it with 11straps?

If not -and we have a bunch of front end components for boostrap 5 - like https://webpixels.io/components - can we these to build out a PIT site? (This seems like something similar enough https://bootstrap-starter-kit.webpixels.work/ ) IDK front end development anymore 🤷‍♂️

**Comment by nniiicc** [comment]
@evamaxfield when you are back can you respond

**Comment by evamaxfield** [comment]
Yea I haven't touched frontend stuff in forever. From my parsing of both 11straps docs + the source code it looks like we ship bootstrap5 with our website so I would assume that we can use whatever bootstrap stuff we want.

If we wanted a different web component framework we could probably add it manually.

All the classes in these files: https://github.com/PugetSoundClinic-PIT/PugetSoundClinic-PIT.github.io/blob/main/src/index.njk

are bootstrap classes.


For the "posts" where we have some central template for each post, its the same: https://github.com/PugetSoundClinic-PIT/PugetSoundClinic-PIT.github.io/blob/main/src/_includes/layouts/post.njk

Does that answer question?

**Comment by nniiicc** [comment]
Somewhat - I guess what I'm wondering is what our next steps are to layout pages - we can certainly borrow some pre-developed front-end components (e.g. a contact page, a "team" page etc... What should we do - create wireframes? Should we hire someone to do this? 

Re posts - do they have to be written in njk? can we use markdown to simplify this?

**Comment by evamaxfield** [comment]
I think for now we should find example pages we like which use bootstrap and then do it ourselves.

sorry about the confusion on `njk` I think that is me.

the only thing that needs to be written in njk is the page templates: https://github.com/PugetSoundClinic-PIT/PugetSoundClinic-PIT.github.io/tree/main/src/_includes/layouts

for example, this about page is currently written in njk but it uses a template so it really good be ported to just use markdown. Don't know why i didn't do that in the first place: https://github.com/PugetSoundClinic-PIT/PugetSoundClinic-PIT.github.io/blob/main/src/about.njk

(`layout: layouts/default.njk`)

here is the template for blog posts: https://github.com/PugetSoundClinic-PIT/PugetSoundClinic-PIT.github.io/blob/main/src/_includes/layouts/post.njk

and here is the markdown for a blogpost: https://github.com/PugetSoundClinic-PIT/PugetSoundClinic-PIT.github.io/blob/main/src/posts/post1.md

let me try to switch the about page to a markdown file as well

**Comment by evamaxfield** [comment]
Update both the "about" and "work with us" pages to be written in markdown: https://github.com/PugetSoundClinic-PIT/PugetSoundClinic-PIT.github.io/commit/76e2f8a2da364cb9483854c28c30a04b50ea9ef4

Hopefully that commit shows how we can make custom templates and use the parameters to fill parts of it and then the rest of the content is just converted and displayed
