### ISSUE TITLE
Civic Technology & Labor Policy research application

### ISSUE THREAD

**Issue by MasonGreen365** [PugetSoundClinic-PIT/PugetSoundClinic-PIT.github.io#30]
Afternoon, 

My name is Mason Green, he/him, and I am a Senior studying Informatics and Political Science. I am extremely interested in working on several of the Puget Sound Clinic's projects, as I am passionate about creating data driven applications to benefit work in public policy, and access to local/state governments!

**Council Data Project**

I am enamored with this project and what it has accomplished so far. I worked as the Director for Legislative Affairs for ASUW last year, and had to navigate the state legislature's antiquated website constantly to gather data and information to paint a picture of legislative support for various student initiatives. During my time in this role, I constantly brainstormed about the ways in which I could improve the experience of advocates, grassroots initiatives, and journalists. These groups often don't have access to paid lobbying software, or expertise in navigating the fast-moving and complex system that is the legislative session. 

Working on the Council Data Project is an exciting opportunity to engage with state/local databases and present information in an intuitive and accessible way for individuals. I personally would love to develop visualizations and interactive models, similar to work that is done at [fivethirtyeight.com](url). Below are three questions about this project:

1. Have you considered integrating state legislative sessions into this application? If so, what are your concerns about the breadth, complexity, and availability of data pertaining to the state legislature?
2. The visual design of CDP's website is excellent. However, I am curious about which user experiences you prioritize when making design decisions. Are you more interested in creating a catalogue that informed individuals can explore with keywords, or have you considered making the website's content more discoverable for individuals without search queries in mind? Essentially, journalists versus a curious Seattle resident. 
3. What local/state agencies have you considered partnering with during this project? If agencies have turned down a proposal to work with you, what are major reasons they provide? I ask this because in my previous role I had to collect data about the Services and Activities (S&A) fee structure across all higher education campuses in WA, and examine similarities and differences. This was for a bill proposal to establish a standardized S&A fee across the state to fund a statewide student association.

I am also interested in the Labor Policy projects on Deactivation and Gig Work and Precarity. I can commit 5-10 hours a week to the project, and would like to work with the group for at least two to three quarters. I can be reached at masongreen511@gmail.com, and am available every morning next week. I have evening classes MW and work F-Sun. I appreciate your time reading through my application and considering my questions. 

Thanks, 

Mason Green

**Comment by nniiicc** [comment]
Hi @MasonGreen365 - I'm going to CC @evamaxfield on this response because she leads the CDP work. 
It sounds like a good fit - I propose the next step is to find a time to meet with Eva and then we can figure out how to get you onboarded for working with the clinic!

**Comment by evamaxfield** [comment]
Hi @MasonGreen365! I would absolutely love to chat. Tomorrow is a holiday but next week I am pretty free:

* Monday until 11:00am (in-person or remote)
* Tuesday after 2:00pm (remote)
* Wednesday the whole day (in-person or remote)
* Thursday after 2:00pm (remote)
* Friday until 1:30pm (in-person or remote)

Let me know what works for you! You can respond here or via email: evamxb@uw.edu

And if you have a moment I would love to see a code sample if possible (homework assignment, prior work, etc.). You can send along in an email if it needs to stay private. Just trying to see where you are at!

I can answer your questions whenever we chat.
