### ISSUE TITLE
Research application: Civic Technology - Wifi Hacking

### ISSUE THREAD

**Issue by xyx0826** [PugetSoundClinic-PIT/PugetSoundClinic-PIT.github.io#31]
Hello! My name is Jack Sui and I'm a senior in Informatics at the UW. I'm a software developer with a strong interest in cybersecurity, digital privacy, and education. I would love to work with the Clinic on several of its research topics as they align perfectly with my skills and my passions of advancing public education on digital security and technology in general.

The one research project that I am extremely interested in is **Wifi Hacking as Cybersecurity Education**. I stumbled upon the world of microcontrollers five years ago and I was blown away by how much computing and communication those tiny computers could do. I also loved how they are an extremely tangible form of computing, unlike web or desktop programs buried deep in a laptop. In fact, I began my microcontroller adventures on the predecessor version of the chip mentioned by that post on The Verge - the ESP8266. During my senior year at high school, I used this Wi-Fi microcontroller to help my friend in an art class create his final project: a lamp in a hallway that everyone passing by could connect to and control through their smartphone. I have worked on numerous personal projects involving microcontrollers in the past years. Today I am part of the UW's Formula SAE racing team, UW Formula Motorsports, and I develop on microcontrollers (ESP8266 included!) on a near-daily basis as the Firmware Team Lead.

Besides my experience with embedded development, I'm also an avid advocate of raising public awareness of online safety. Several of my family members and friends have had experiences with phishing and data leaks. Helping them out made me realize how important it is for me to help my communities understand the importance of cybersecurity and how it relates to their lives. When I design and build web apps, I have made a habit of always treating security as the number one goal and continuously thinking of ways to give my attackers a really bad day. This research project seems like a perfect opportunity for me to combine my knowledge of embedded programming, my passion for raising cybersecurity awareness, and my interest in ethical hacking into a fun way to expose folks to privacy and security concepts and increasing cybersecurity outreach.

With that being said, I have a couple questions regarding this project:

* What population does this research project target? There is an emphasis on instruction through hardware, but hardware building isn't for everyone. Some people aren't keen to assembling electronics by hand, while others who might otherwise be interested in this topic tend to steer away from having to buy parts, in contrast to free/open-source software. How does this project define its target audience to strike the balance between the novelty and interactivity of hands-on education versus its complexity and required efforts?
* Although Wi-Fi hacking is ethical under the scope of this project, it is still, well, hacking. Modern Wi-Fi hotspots tend to default to strong encryption so that unauthorized password retrieval is less likely, but deauth attacks can still seriously disrupt Wi-Fi networks. How does this project address the fact that the Wi-Fi attack techniques taught for educational purposes can be abused for actual hacking or pranking?
* There are already many ESP8266/ESP32-based platforms for interacting with Wi-Fi networks, such as the HakCat mentioned by The Verge, the famous [esp8266_deauther](https://github.com/SpacehuhnTech/esp8266_deauther), and an array of similar hardware from USB keys all the way to watches on Amazon. Does this project aim to build on an existing hardware solution or make one from scratch?

I can devote \~5 hours per week for the rest of Fall 2022 (in person) through Winter 2023 (remote), then 10~20 hours per week for Spring 2023 (in person). My email is `jacksui [at] [uw]`, and my availability is as follows:

* Fri, Nov 11: all day
* Sat, Nov 12: before noon
* Sun, Nov 13: all day
* Mon, Nov 14: before noon, and 5:30pm onwards
* Tue, Nov 15: before 9am, and 5pm onwards
* Wed, Nov 16: before 9am
* Thu, Nov 17: 5pm onwards

Please let me know if any or none of these works. Thanks for considering my application and question. I'm very excited to learn more about this project and am looking forward to working with the Puget Sound Clinic! -Jack

**Comment by nniiicc** [comment]
Hi Jack - sounds like a great fit. Let me take a look at my schedule next week and propose a time with you. 
Thanks!

**Comment by xyx0826** [comment]
Gentle reminder on this issue. Looking forward to talking to you more about this project!

**Comment by xyx0826** [comment]
Nudging this again. :smile: I hope you've had an awesome Thanksgiving break. I know how easily things can get lost in the mix!
